version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: activamente_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/activamente_prod"
      SECRET_KEY_BASE: "changeme" # Generate a real secret with: mix phx.gen.secret
      PHX_HOST: "localhost"
      PORT: 4000
      MIX_ENV: prod
      # Add your API keys here
      # OPENAI_API_KEY: "your_openai_key"
      # ANTHROPIC_API_KEY: "your_anthropic_key"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: